### ISSUE TITLE
CLI in dev mode + AWS S3 file storage

### ISSUE THREAD

**Issue by TaiKamilla** [shopware/production#10]
Hi
If you install the SW6 from the production repo from GitHub, through the CLI in dev mode, and try to set AWS S3 as file storage, the storefront does not build path to the style sheet correctly
instead of `myawsbucket.com/theme/.../all.css` it does `/theme/.../all.css`
It works for images and other assets, and the css is there in the bucket
Any ideas?

UPDATE:
It seems that is known bug, is going to be updated on next release
https://issues.shopware.com/issues/NEXT-6651

**Comment by jleifeld** [comment]
Hi @TaiKamilla ,

thank you for submitting the issue :) 

As you already posted we are known of this issue. An easy workaround is not possible yet. Therefore you have to wait for the fix from our side.

Jannis

**Comment by suchmaske** [comment]
Are there any updates about this issue? I am currently facing the same problem as @TaiKamilla. I am running Shopware v6.4.7.0
