### ISSUE TITLE
Can't setup environment

### ISSUE THREAD

**Issue by Zerotask** [shopware/production#101]
After cloning and switching to the directory I tried running `bin/console system:setup` and the following commands, but I always get the error
![image](https://user-images.githubusercontent.com/20150243/117027809-581e0d80-acfd-11eb-9b85-5d97db12e894.png)

There is just a .env.dist and no .env file. There is no step described that you have to create an own .env, it just says
> **or** create .env yourself, if you need more control

**Comment by mynameisbogdan** [comment]
Try running something like `APP_URL=http://shopware.local bin/console system:setup`

**Comment by Zerotask** [comment]
@mynameisbogdan thank you, this is working.

This should be documented although.

**Comment by shyim** [comment]
Is fixed in the trunk will be released with 6.4.1.0
