### ISSUE TITLE
google-shopping.xml couldn't be generated

### ISSUE THREAD

**Issue by steven-codegasm** [shopware/production#102]
The following nginx location rule bypasses the shopware route `/store-api/product-export/{accessKey}/{fileName}`, when fileName its a xml file

https://github.com/shopware/production/blob/78b42e8ad9f1f541bdda2f6df8e4f07805447bd3/config/etc/nginx/nginx.conf#L74

**Comment by shyim** [comment]
https://github.com/shopware/production/commit/0abd78c0aad642ae5a8654772e3902a9d59c0031
