### ISSUE TITLE
Update 6.4.2.1 to 6.4.3.0 and 6.4.3.1 fails at unpacking

### ISSUE THREAD

**Issue by danielgoodbits** [shopware/production#112]
### PHP Version

7.4.19

### Shopware Version

6.4.2.1

### Expected behaviour

Update runs through smoothly.

### Actual behaviour

Unpacking of the update zip fails with a 500 error near the end of unpacking:

![image](https://user-images.githubusercontent.com/76940824/128020888-dfd9eff8-7761-4688-be3c-d71b8a8d00db.png)

### How to reproduce

We are running it with the docker-compose file in this repo. 
An then using the auto-updater in the admin interface.

Only change in docker-compose is that we include the whole directory:
```
volumes:
      - "${PWD}:/sw6"
```

**Comment by shyim** [comment]
Is known and fixed already: https://github.com/shopware/platform/commit/cd55b77bc3edfb5897ef51305eb47b8dc33350ab

When you use composer-based setup. Don't use the updater and run composer update

**Comment by danielgoodbits** [comment]
For this one is not closed. Newest version 6.4.3.1 is failing too and a composer update is not working neither.
