### ISSUE TITLE
Zusatzfelder SELECT Type

### ISSUE THREAD

**Issue by cmg193** [shopware/production#116]
### PHP Version

7.4

### Shopware Version

6.4.4.0

### Expected behaviour

Erwartet wird dass nach der Installation der Plugin einen Zusatzfeld erstellt wird mit:
- **Setname**: cat_ext
- **Name**: dos_menu_template
- **Typ** Select Feld
- **Optionen** :"list-drill" und "list"
- **Entität**:  Kategorien 
- **Sprachen**: in alle Sprachen pflegbar sein.

### Actual behaviour

Wird alles richtig gemacht bis auf:
- der hacken **"In allen Administrationssprachen pflegen"**  ist nicht aktiv. Übersetzung ist da aber der hacken ist nicht gesetzt
- Optionen: Das Select Feld wird falsch Konfiguriert (nehme an). In die Set Informationen sind die Optionen nicht sichtbar. In die Kategorie Übersicht wo die Felder zu erwarten sind, dreht sich die Ladeanimation unendlich. 
Sehe Schreenshots:

**Set Informationen**
1: ![image](https://user-images.githubusercontent.com/56188324/133058012-417ab4dd-6dc0-4c52-a2cc-ac6fab551cbe.png)
2: ![image](https://user-images.githubusercontent.com/56188324/133058100-84cbe0d3-cfef-41a6-b0c7-25a3c04a9b6f.png)

**Kategorie Übersicht**
![image](https://user-images.githubusercontent.com/56188324/133058292-dc0b55c5-1251-4bc9-8f40-13f01fb7f67f.png)

In der **Datenbank** wird folgendes geschrieben:
1.  custom_field
![image](https://user-images.githubusercontent.com/56188324/133059076-8bced7ed-3ce2-43be-93ce-6c1418631700.png)

2. custom_field_set 
![image](https://user-images.githubusercontent.com/56188324/133059190-fda1ec3a-1c61-4bd7-ae39-fbf1558a7569.png)

### How to reproduce

Einfach eine neue Instanz von Shopware 6.4.4.0 aufsetzen, 

- einen Theme Plugin Schreiben 
- Bootstrap PHP erweitern mit 

```php
...
public function install(InstallContext $context): void
    {
        $customFields = [
            [
                'name' => 'cat_ext',
                'translated' => true,
                'config' => [
                    'label' => [
                        'de-DE' => 'Kategorien Erweiterung',
                        'en-GB' => "Category Extension"
                    ],
                    'customFieldPosition' => 2,
                ],
                'customFields' => [
                    [
                        'name' => 'dos_menu_template',
                        'type' => 'select',
                        'label' => [
                            'de-DE' => 'Menu Anzeige der Kategorie',
                            'en-GB' => 'Category display type',
                        ],
                        'active' => true,
                        'options' => [
                            [
                                'label' => [
                                    'de-DE' => 'Erweiterte Liste',
                                    'en-GB' => 'Drill List',
                                ],
                                'value' => 'list-drill',
                            ],
                            [
                                'label' => [
                                    'de-DE' => 'Liste',
                                    'en-GB' => 'List',
                                ],
                                'value' => 'list',
                            ],
                        ],
                    ]
                ],
                'relations' => [
                    ['entityName' => 'category']
                ]
            ]
        ];

// 1. versuch
//        foreach ($customFields as $customFieldSet) {
//            $repo->upsert([$customFieldSet], $context->getContext());
//        }
// 2. versuch
//        /** @var \Shopware\Core\Framework\DataAbstractionLayer\EntityRepository $repo */
//        $repo = $this->container->get('custom_field_set.repository');
//       $repo->create($customFields, $context->getContext());
}
...
```

Bei beide Code Versuche kommt dasselbe Ergebnis.

Mache ich da was falsch?

Plugin Installiere und Aktivieren.
Wobei nur die Installation sollte auch reichen

**Comment by amenk** [comment]
Ich glaube das ist besser als Frage im Forum, auf StackOverflow, oder - wenn es ein Bug - ist in https://github.com/shopware/platform/ oder issues.shopware.com aufgehoben :-)

**Comment by shyim** [comment]
See answer from @amenk
