### ISSUE TITLE
Categories can't be saved in Backend

### ISSUE THREAD

**Issue by cfreak** [shopware/production#119]
### PHP Version

7.4

### Shopware Version

v6.4.5.1 Stable Version

### Expected behaviour

Categroy can be saved in Backend if you assign a Layout.

### Actual behaviour

Category can't be saved and throws an error in the JS Console:

app.js?16335316765871527:1 

An error was captured in current module: TypeError: Cannot read properties of undefined (reading 'locked')

### How to reproduce

Try to save a category with a new layout

**Comment by MrSnoozles** [comment]
Can confirm, in 6.4.5.0 and 6.4.5.1 the shop owner can not update / save categories anymore. 😞

**Comment by cfreak** [comment]
You find any solution for that?

**Comment by MrSnoozles** [comment]
Not yet. I thought this issue would be serious enough that Shopware would provide a fix by today.

**Comment by tinect** [comment]
You might want to submit the issue in the related repository (https://github.com/shopware/platform/) or better using the issue tracker.

But this issue has been resolved already:
https://github.com/shopware/platform/commit/55b80c0c7155dfaad1776e34fe9a60cb25931446

**Comment by cfreak** [comment]
Do you know, how i can fix the issue in my system, or do i have to wait until the next release?

**Comment by tinect** [comment]
> Do you know, how i can fix the issue in my system, or do i have to wait until the next release?

You can fix it in your shop manually and compile the administration. Or wait for a release :-)

**Comment by Carlit0** [comment]
Looks like 6.4.6.0 still has the problem.

**Comment by keulinho** [comment]
The issue should be resolved in 6.4.6.0, please ensure that the new administration assets are loaded and that you don't accidentally use the asstets of the older version.

**Comment by Carlit0** [comment]
You are right! It has been fixed! @keulinho 
I just looked at the changelog, my bad.

**Comment by keulinho** [comment]
This issue has been resolved already in 6.4.6.0:
shopware/platform@55b80c0
