### ISSUE TITLE
Better extendability for sytem:setup command and extend the one from MaintenanceBundle

### ISSUE THREAD

**Issue by AndreasA** [shopware/production#122]
### Please describe the feature you would like to see implemented.

Instead of copying the command from the MaintenaceBundle it would be better if it would just extend the one from the MaintenanceBundle and add some extendability options like some protected methods that could be overridden, e.g. to add custom env variables etc. just before confirmation.

it would also make it easier to update those commands.

**Comment by mitelg** [comment]
we are completely moving such commands and scripts to the platform repository.
the ones in the production template are still there, due to backward compatibility reasons. and will be removed in the future.
correct me if I'm wrong @keulinho

**Comment by AndreasA** [comment]
@mitelg It makes sense to move them there completely. 

However, maybe you could add two events to the setup command:

- One just before the env file is written (prior to the confirm check) to add additional env values or adjust existing ones.
- Two an option to adjust the default env values (inside the getDefault method)

That way the command is easily customizable for a project.


Regarding backward compatibility, just wondering but the commands have to be manually updated by copying the new files to an existing project, so wouldn't removing them and adding the Maintenance bundle be easier for a user during the update/upgrade process?

**Comment by shyim** [comment]
https://github.com/shopware/production/commit/4a0cd7c022c3971d7e8dacaa4a1ec5fa6c954f2e

We had it in pipeline already for months is now merged :sweat_smile:
