### ISSUE TITLE
.env.dist still references swiftmailer

### ISSUE THREAD

**Issue by AndreasA** [shopware/production#124]
### PHP Version

7.4

### Shopware Version

6.4

### Expected behaviour

Not that important but in the https://github.com/shopware/production/blob/v6.4.6.1/.env.dist#L13 there are still references to swiftmailer bundle for the mailer URL.

you can probably remove the comments altogether though as you do not really support symfony flex anyway - especially for the mailer/framework config.

the same goes for `symfony/framework-bundle`.

I admit it is mostly a cosmetic fix.

Also: Is the dist file actually necessary? The setup command e.g. completely ignores it and I think the installation through the PHP interface could also ignore it (if it doesn't do so already).

### Actual behaviour

see above.

### How to reproduce

see above.

**Comment by shyim** [comment]
I have removed it
