### ISSUE TITLE
.env.local / .env.{environment} / .env.{environment}.local - Support missing from admin/storefront watch and build tasks

### ISSUE THREAD

**Issue by AndreasA** [shopware/production#128]
### PHP Version

7.4

### Shopware Version

6.4.7.0

### Expected behaviour

The watch and build tasks for admin and storefront should also support the `.env.local` and `.env.{environment}` and `.env.{environment}.local` syntax as the PHP code now does.

Not 100% sure how to best fix it. one solution would be to manually check the source file chain the same way as DotEnv does or use DotEnv to generate the ENV parameters and export them (if easily possible).

### Actual behaviour

Currently at least the watchers only load .env files:
https://github.com/shopware/production/blob/86bf952a8ad48fb939483e0db2bb2c530c063735/bin/watch-storefront.sh
https://github.com/shopware/production/blob/86bf952a8ad48fb939483e0db2bb2c530c063735/bin/watch-administration.sh

### How to reproduce

See expected behaviour.

**Comment by mynameisbogdan** [comment]
Indeed here it's a BC break.

**Comment by shyim** [comment]
Is done in new template https://github.com/shopware/recipes/commit/0e4fc569a42e38364ecc711928a44d4a6c4134c2
