### ISSUE TITLE
.env.dist should be renamed to .env and the setup command should generate a .env.local file instead

### ISSUE THREAD

**Issue by AndreasA** [shopware/production#129]
### PHP Version

7.4

### Shopware Version

6.4.7.0

### Expected behaviour

Now that you started to support .env.local it should be the default way to go, so the setup command should generate a `.env.local` file an the `.env.dist` should be renamed to `.env`.

Also created: https://github.com/shopware/platform/issues/2249

### Actual behaviour

Command still generated .env file and the project contains a .env.dist file.

### How to reproduce

See expected behaviour and actual behaviour.

**Comment by AndreasA** [comment]
no need to wait for 6.5 as long as the previous .env loading is still supported in the core as the files from here nobody needs to update.

**Comment by shyim** [comment]
I guess thats done already with https://github.com/shopware/production/commit/86bf952a8ad48fb939483e0db2bb2c530c063735
