### ISSUE TITLE
.gitignore is missing .env.local and .env.*.local but still contains .env

### ISSUE THREAD

**Issue by AndreasA** [shopware/production#130]
### PHP Version

7.4

### Shopware Version

6.4.7.0

### Expected behaviour

See title, the gitignore file does not include .env.local and .env.*.local

It might also make sense to remove .env once the system setup command also supports generation of .env.local.

### Actual behaviour

gitignore is missing  .env.local and .env.*.local

### How to reproduce

just check the file

**Comment by mynameisbogdan** [comment]
`.env` should be used a base configuration with default values that you can commit, so it doesn't quite make sense to remove it. Also when used with `symfony/flex` new default configuration is added to `.env` when you install a new package for that specific package.

Example `.gitignore` for `symfony/framework-bundle`:

```
###> symfony/framework-bundle ###
/.env.local
/.env.local.php
/.env.*.local
/config/secrets/prod/prod.decrypt.private.php
/public/bundles/
/var/
/vendor/
###< symfony/framework-bundle ###
```

**Comment by AndreasA** [comment]
Which is exactly what I mean? 
The current gitignore here, has `.env` in it but not `.env.local` and not `.env.*.local` and also not `.env.local.php`.  

So `.env` will not be commited to git but `.env.local` etc. will be which is not correct with new setup: https://github.com/shopware/production/blob/0a8281a40a8bd88a07be9ed3e63e56401d19426b/.gitignore#L40

furthermore, the `.env.dist` still exists: https://github.com/shopware/production/blob/0a8281a40a8bd88a07be9ed3e63e56401d19426b/.env.dist 
which should be removed as well.

**Comment by mynameisbogdan** [comment]
You're correct, `.env.local` should not be commited but `.env` should. `.env.dist` serves no real purpose.

**Comment by shyim** [comment]
The new template uses flex + runtime. So this is included there and I would not break the behavior here. 

https://github.com/shopware/docs/pull/760/files#diff-2525a2629f134228fc7d55615d5fbb517990de2c6ff9de903d5522d9fd25acf7
