### ISSUE TITLE
Use of PHP 8 in delivered Dockerfile

### ISSUE THREAD

**Issue by ArjanLankhaar** [shopware/production#131]
### Please describe the feature you would like to see implemented.

Hi,

I wonder whether you will be updating the current Dockerfile to be supporting PHP8 any time soon? Or maybe add a second one like Dockerfile.php8 so we can still choose which PHP version we want to use.

**Comment by omaratdgtl** [comment]
any progress on this one?

**Comment by shyim** [comment]
I would not change that Dockerfile anymore. The new template uses https://hub.docker.com/r/webdevops/php-apache, so we don't have to maintain a docker image anymore.

The new template: 
https://github.com/shopware/docs/pull/760/files#diff-2525a2629f134228fc7d55615d5fbb517990de2c6ff9de903d5522d9fd25acf7
