### ISSUE TITLE
.env.<enviornment> etc. incorrectly loaded in bin/console

### ISSUE THREAD

**Issue by AndreasA** [shopware/production#134]
### PHP Version

7.1

### Shopware Version

6.4.7.0

### Expected behaviour

Load `.env.<environment>` and `.env.<environment>.local` correctly according to supplied `--env` parameter or APP_ENV (depending on `--env`  being set).

In order to fix this, please check: https://github.com/symfony/demo/blob/v1.6.4/bin/console or maybe even switch to symfony runtime: https://github.com/symfony/demo/blob/v2.0.1/bin/console and https://github.com/symfony/demo/blob/v2.0.1/public/index.php

### Actual behaviour

`--env` is ignored and the value of `.env.local` is used or `APP_ENV`.

### How to reproduce

- Place `APP_ENV=dev` into `.env.local`.
- Put `APP_URL=https://shopware.com`  into `.env`
- Create a `.env.dev` file and add `APP_URL=https://foobar.localhost` as its content.
- Call `bin/console --env=prod`.
- Check `$env` and `$_SERVER['APP_URL']` in `bin/console` at its last line (e.g. with XDebug).

The content of `$_SERVER['APP_URL']` will now be `https://foobar.localhost` although according to `--env=prod` that file should not have been loaded.

if one uses `APP_ENV=prod bin/console` it works correctly but it should work corectly in all scenarios.

**Comment by AndreasA** [comment]
this will probably be taken care of automatically if you intend to switch to symfony/runtime.

**Comment by shyim** [comment]
We use in new template symfony/runtime :)
