### ISSUE TITLE
Build Pipeline not Installing Plugin NPM Dependencies

### ISSUE THREAD

**Issue by arminlinzbauer** [shopware/production#141]
### PHP Version

^7.4||8.*

### Shopware Version

\>=6.3

### Expected behaviour

As outlined here https://developer.shopware.com/docs/guides/plugins/plugins/plugin-fundamentals/using-npm-dependencies it is possible to include custom npm dependencies in plugins. The help doc explains how to integrate the custom dependencies using aliases, but it doesn't mention that you have to manually install the dependencies before running the build pipeline.

Please either add this very important information to the docs or better yet - give us a way to let shopwar etake care of installing the dependencies on its own. You could just check if a given plugin/src/Resources/app/<storefront|administration> directory contains a package.json file and then perform the npm install task automatically before continuing with the build process...

### Actual behaviour

Build just fails because it can't resolve the custom dependencies if you don't run npm install inside your plugin first.

### How to reproduce

Follow the guide https://developer.shopware.com/docs/guides/plugins/plugins/plugin-fundamentals/using-npm-dependencies

**Comment by shyim** [comment]
Do you have JQ installed?

**Comment by shyim** [comment]
Closing as inactive
