### ISSUE TITLE
shopware.store.frw should be set through e.g. config/packages/shopware.yaml (shopware config) instead of config/services/defaults.xml

### ISSUE THREAD

**Issue by AndreasA** [shopware/production#142]
### PHP Version

8.1

### Shopware Version

6.4.8.1

### Expected behaviour

Instead of providing a parameter use the shopware config instead.
this is relevant because if one changes it via the config it doesn't work as the parameter is overridden in the config/services/defaults.xml file

### Actual behaviour

services/defaults.xml file overrides the provided config `shopware.store.frw`.

### How to reproduce

See referenced files.

**Comment by shyim** [comment]
Is done in new template https://github.com/shopware/recipes/blob/main/shopware/core/6.4/manifest.json#L35
