### ISSUE TITLE
NEXT-20852: Should use EnviornmentHelper as well in bin/console and public/index.php

### ISSUE THREAD

**Issue by AndreasA** [shopware/production#148]
### PHP Version

8.1

### Shopware Version

trunk

### Expected behaviour

It isn't that important but it would be good to keep using EnvironmentHelper whenever env variables are accessed, even in bin/console and public/index.php - especially to support transfomers.

I admit the transformer is probably not really helpful/necessary for COMPOSER_PLUGIN_LOADER and DISABLE_EXTENSIONS flags but there shouldn't be a reason not to use them either.

### Actual behaviour

see https://github.com/shopware/platform/commit/18ca01899b8938ce406c056af6ebff893546aae2#diff-5acf22e4d8719fb5d8c5d67dd935b5e6276e8fa6acf528241cda2988cfb59760R53
https://github.com/shopware/platform/commit/18ca01899b8938ce406c056af6ebff893546aae2#diff-ab1615a3a159df0750aa7b76472124966ab3076c26abcd050f6b9120fbda6c61R46
https://github.com/shopware/production/commit/418b2eae51d33ab65d0352813c71f44ce0fff628#diff-bba48e21b800d26fe8a6cddd7360abba7c76cead6be113086e876f06aff39ff3R65
https://github.com/shopware/production/commit/418b2eae51d33ab65d0352813c71f44ce0fff628#diff-ab1615a3a159df0750aa7b76472124966ab3076c26abcd050f6b9120fbda6c61R70

### How to reproduce

see above

**Comment by shyim** [comment]
We switch to Symfony Runtime and have to not worry about that anymore https://github.com/shopware/recipes/blob/main/shopware/core/6.4/public/index.php
