### ISSUE TITLE
bin/watch-administration.sh for custom docker

### ISSUE THREAD

**Issue by bvgdeveloper** [shopware/production#151]
### Please describe the feature you would like to see implemented.

I'm using devilbox to deploy the shopware 6 project. When I run the bin/watch-storefront.sh script, everything suits me. However, when I run bin/watch-administration.sh I don't see the changes I make to the admin panel. Although the terminal is compiling. Is it possible to set up a proxy for viewing behind the admin panel by analogy with the side front? Or is there some other solution

**Comment by shyim** [comment]
Is maybe the websocket connection not connected?

**Comment by shyim** [comment]
Closing due inactive
