### ISSUE TITLE
[error] SWAG_MIGRATION_RUN_EXCEPTION in logs while migrating..

### ISSUE THREAD

**Issue by emson-softound** [shopware/production#156]
### PHP Version

8.1

### Shopware Version

6.4.13

### Expected behaviour

Data migrated successfully and visible in the backend/frontend.

### Actual behaviour

Migrated data doesn't appear to visible in backend/frontend and there are errors within the logs.

### How to reproduce

I am trying to migrate from shopware 5.7 with demo-data to shopware 6.4 in my local development environment within a virtual environment.
I had followed all instructions mentioned in the site
https://docs.shopware.com/en/migration-en/Migrationprocess?category=migration-en/shopware5
I had used local gateway setup for this.

Although the status of migration is 'success'. No migrated data is visible in backend of shopware 6.4 and there are errors within the logs in migration process. I have attached a log for reference.
[migrationRunLog-a482eb6d80df4ca3bb4c5e760b0237a3.txt](https://github.com/shopware/production/files/9221540/migrationRunLog-a482eb6d80df4ca3bb4c5e760b0237a3.txt)

**Comment by shyim** [comment]
Please create an issue in the issue tracker at https://issues.shopware.com
