### ISSUE TITLE
src/TestBootstrap.php references DG\BypassFinals

### ISSUE THREAD

**Issue by 0x4** [shopware/production#159]
### PHP Version

8.1

### Shopware Version

6.4.15.1

### Expected behaviour

every use statement has a composer package

### Actual behaviour

src/TestBootstrap.php has a reference to DG\BypassFinals - but that package was removed from composer.json in this commit https://github.com/shopware/production/commit/2ba5f9e99013da98b04c05555e8c95923a097309

### How to reproduce

n/a

**Comment by shyim** [comment]
there is now an if around https://github.com/shopware/platform/blob/trunk/src/Core/TestBootstrapper.php#L65
