### ISSUE TITLE
Dependency Definition for Easy-Coding-Standard

### ISSUE THREAD

**Issue by mralexandernickel** [shopware/production#166]
### Please describe the feature you would like to see implemented.

Since you guys are adding a configuration (`easy-coding-standard.php`) inside the repository, I think it would make sense to also add the version with which the config-file is working to composer.json as dev-dependency. Otherwise one can just guess which version is needed to be able to use the provided confiuration

**Comment by shyim** [comment]
Hey,

with the new template we don't have that file anymore. So feel free to overwrite that fiel or delete it :)

https://www.shopware.com/en/news/shopware-goes-symfony-flex/
