### ISSUE TITLE
Installation instructions do not work

### ISSUE THREAD

**Issue by freesoul** [shopware/production#167]
### PHP Version

8

### Shopware Version

last

### Expected behaviour

The instructions are correct

### Actual behaviour

When you do the first step (composer install), then "pre-install-cmd" is triggered, which runs the file bin/console, which reads ../vendor/autoload.php, which does not exist yet, because it is a pre-install of composer packages.

### How to reproduce

just clone the project and run composer install

**Comment by shyim** [comment]
Hey,

in the meanwhile we switched to Symfony Flex and we don't have that `pre-install-cmd` anymore.
