### ISSUE TITLE
Install with composer 2.5.0 not work

### ISSUE THREAD

**Issue by DevertNet** [shopware/production#168]
### PHP Version

8.1

### Shopware Version

6.4.18.0

### Expected behaviour

A fresh clone of shopware/production and a `composer install` works without a problem.

### Actual behaviour

`composer install` run into the following error:
```
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
- Required package "shopware/core" is not present in the lock file.
- Required (in require-dev) package "phpunit/phpunit" is in the lock file as "9.5.2" but that does not satisfy your constraint "~9.5.17".
This usually happens when composer files are incorrectly merged or the composer.json file is manually edited.
Read more about correctly resolving merge conflicts https://getcomposer.org/doc/articles/resolving-merge-conflicts.md
and prefer using the "require" command over editing the composer.json file directly https://getcomposer.org/doc/03-cli.md#require
Script @composer install --working-dir vendor/shopware/recovery --no-interaction --no-scripts handling the post-install-cmd event returned with error code 4
Error: Process completed with exit code 4.
```

The problem is that composer 2.5.0 (20.12.2022) changed the following:
`Added hard failure when installing from a lock file which does not satisfy the composer.json requirements`
https://github.com/composer/composer/blob/main/CHANGELOG.md

It looks like that the composer.json und composer.lock file of shopware/recovery does not match.

### How to reproduce

1. Clone shopware/production and switch to version 6.4.18.0
2. Fire `composer install`

**Comment by DevertNet** [comment]
As workaround you can change your composer version with this command to the last working version:
`composer self-update 2.4.4`
I need this workaround in my CI :D

**Comment by shyim** [comment]
Hey,

We can't really fix it for the older versions. But we will fix it for the next minor release.

For now you have three options to fix this:

## Removing shopware/recovery (Recommended)

The recovery package contains only the Updater logic for the Web Updater. This is not required for composer based updates.

### Update your composer.json

```diff
"scripts": {
        "pre-install-cmd": [
            "[ ! -f vendor/autoload.php ] || $PHP_BINARY bin/console system:update:prepare"
        ],
        "pre-update-cmd": [
            "[ ! -f vendor/autoload.php ] || $PHP_BINARY bin/console system:update:prepare"
        ],
        "post-install-cmd": [
-           "@composer install --working-dir vendor/shopware/recovery --no-interaction --no-scripts",
-           "@composer install --working-dir=vendor/shopware/recovery/Common --no-interaction --optimize-autoloader --no-suggest",
            "[ ! -f vendor/autoload.php ] || $PHP_BINARY bin/console system:update:finish"
        ],
        "post-update-cmd": [
-           "@composer install --working-dir vendor/shopware/recovery --no-interaction --no-scripts",
-           "@composer install --working-dir=vendor/shopware/recovery/Common --no-interaction --optimize-autoloader --no-suggest",
            "[ ! -f vendor/autoload.php ] || $PHP_BINARY bin/console system:update:finish"
        ]
    }
```

```diff
    "require": {
        "php": "^7.4.3 || ^8.0",
        "composer-runtime-api": "^2.0",
        "shopware/administration": "~v6.4.0",
        "shopware/core": "~v6.4.0",
        "shopware/elasticsearch": "~v6.4.0",
-       "shopware/recovery": "~v6.4.0",
        "shopware/storefront": "~v6.4.0"
    },
```

## Update to Flex Template

The Flex template does not contain the Recovery anymore. https://www.shopware.com/en/news/shopware-goes-symfony-flex/

## Run composer update inside that folder

By calling update, you generate a newer lock file and then finally can run it.

```bash
composer update -d vendor/shopware/recovery/Common/
```

**Comment by Schrank** [comment]
Fourth Alternative: stay on composer 2.4.4

**Comment by aragon999** [comment]
The obvious fix would be to release a new patch version for each affected minor version.

**Comment by philipschikora** [comment]
Is there any update on this issue?

**Comment by shyim** [comment]
I will close this as in newer versions this has been fixed

**Comment by VPysarenko-nme** [comment]
I've installed 6.4.20.0 and I have the exact same problem

**Comment by philipschikora** [comment]
the fix above works for now

**Comment by mikewink** [comment]
@shyim thank you for the fix!

Can/Should I update to the new Flex template while using Shopware 6.4.x or will that be done for me with the upgrade to 6.5.x? And if I should update, where do I find more information about the process?

Thank you

**Comment by shyim** [comment]
The auto updater will migrate to flex. You can use the new installer to migrate to >= 6.4.18.0
