### ISSUE TITLE
6.5 RC with symfony flex

### ISSUE THREAD

**Issue by DevertNet** [shopware/production#173]
### Please describe the feature you would like to see implemented.

Hello,

is it possible to use 6.5 RC with the Symfony Flex template?
That would make testing much easier, especially since there will probably be a few more RC relaeses for 6.5.
This would also make it easier to pre-test new versions in the future.

I have posted this here rather than in Slack as I suspect several people are asking this question.

**Comment by shyim** [comment]
With `composer create-project shopware/production:6.5.0.0-dev` you can create a new Shopware Project with Symfony Flex.

Any new RC can be updated by running `composer update`
