### ISSUE TITLE
Release for 6.5.1.0?

### ISSUE THREAD

**Issue by momocode-de** [shopware/production#176]
When will 6.5.1.0 be available as a version here? We can't create a project with `composer create-project shopware/production:v6.5.1.0`  right now.

Background: I want to test my plugin in a Github workflow for all Shopware versions. For this I have defined the Shopware versions in a matrix and write the matrix variable as version in the composer command. Therefore I need exactly this version. And for that I think a new release has to be created here in this repo.

Or is there a reason why this has not been done until now?

**Comment by andrepayone** [comment]
I'm facing the same problem since I need a tarball from the releases/tags section for 6.5.1.0 releases the way they used to be all the time before. 
Is this repo deprecated or abandoned? The way Shopware is recommended to be installed in the docs (Mix local/docker, devenv, shopware-installer) is simply insufficient for my needs.

**Comment by ndzoesch** [comment]
Hey folks,

as it stands rn, this repository is mainly there to hold the `composer.json`  that requires Shopware.
We will make changes to communicate this more clearly.

So this repo is not abandoned, but installing a specific Shopware version works differently after the switch to flex.

You can of course always use the in-browser method, but I guess you are looking for a CLI solution.
What you can do is:

1. [Create a project](https://developer.shopware.com/docs/guides/installation/template), then change the `composer.json` manually, then `composer update`

OR

2. [Create a project](https://developer.shopware.com/docs/guides/installation/template), then: `composer req shopware/core:6.5.1.0 shopware/administration:6.5.1.0 shopware/elasticsearch:6.5.1.0 shopware/storefront:6.5.1.0 -W` (fill in the version you need)

OR

4. run `shopware-cli project create <project-name>` interactively or run non-interactive and [pass the version as parameter](https://sw-cli.fos.gg/commands/project/).

Where the third option is the one you are looking for, I guess.
I will close the issue for now, if there are further questions feel free to reopen. 

Cheers, Niklas 💙 

[edited for clarity]
