### ISSUE TITLE
Rename .gitkeep to gitignore for consistency with recipes

### ISSUE THREAD

**Issue by ioanok** [shopware/production#177]
In `custom/plugins` and `custom/static-plugins` there is a `.gitkeep` file, but the recipes are coming with a `.gitignore` file and you will get both once you create a new project with command `composer create-project shopware/production <project-name>`.

So, `.gitkeep` should be renamed with `.gitignore` in order to be consistent with recipes.
Please, have a look on this commit https://github.com/shopware/recipes/commit/965249e697e14d3e7131917eff5367b64c5a55d7

Also, `.gitignore` from the recipe should be updated.

**Comment by shyim** [comment]
Is merged, thanks!
