### ISSUE TITLE
Action "Update Tags" failed

### ISSUE THREAD

**Issue by carstenjaksch** [shopware/production#180]
Hi,

the [recently added workflow](https://github.com/shopware/production/commit/b97ae2002387faf504fd3710d879899f13874116) "update tags" fails with the following message on step "Push missing tags":

```
/home/runner/work/_temp/8c41e79e-e0dd-41ab-9b53-8ec0f528c65a.sh: line 1: ./update.sh: Permission denied
Error: Process completed with exit code 126.
```

It is a fresh repository (private) based on this guide about [Symfony Flex](https://developer.shopware.com/docs/guides/installation/template.html).

Interestingly, the step "Push missing tags" does not exist in the workflow file. There are only "Create missing tags" and "Push tags".

We do not have a GitHub subscription yet and I think only public repositories have free action minutes. Could that be the issue here?

**Comment by shyim** [comment]
We fixed that thanks for the info :)
