### ISSUE TITLE
Action "Update Tags" fails again since two months

### ISSUE THREAD

**Issue by carstenjaksch** [shopware/production#184]
See screenshot for error messages. The problem seems to occur since tag v6.6.6.1.

I have checked if the code for that action changed, but it is the same. No clue why it works in this repo.

![Image](https://github.com/user-attachments/assets/ed9eda33-7f31-4236-aac3-88293ee62c7d)

**Comment by shyim** [comment]
You don't need that action inside your repository. By mistake the workflow was added to the projects for a while, we fixed that with https://github.com/shopware/production/commit/3a45d9f9c374fdc2cca5166717d4c11411eed7fd

**Comment by carstenjaksch** [comment]
Thanks, I will remove that action.
