### ISSUE TITLE
.env.dist has wrong environment variable names

### ISSUE THREAD

**Issue by bestit-ewieser** [shopware/production#19]
In the [.env.dist](https://github.com/shopware/production/blob/6.1/.env.dist#L26-L29) file the ElasticSearch environment variables still contain the string "_SES_", which was changed to "_ES_" quite some time ago:

https://github.com/shopware/development/commit/e7e55b8631b8a8261312702361ceb5494a1e35d6#diff-5d6aaa818bfced97dd2a2418a00d6af3

**Comment by pweyck** [comment]
Hello @bestit-ewieser,

thanks for the feedback. Do you use the file as a template? It's an old leftover and is not used by any script in the project (was copied from the development template). If it's used as a reference, we should fix it.

**Comment by bestit-ewieser** [comment]
Hi @pweyck ,
yes, we are using it as a template to create the .env file upon deployment and fill it with the values from ENV-parameters configured in our Bitbucket-Pipelines deployment pipeline.
Is there anything you have in mind to advise us against doing so?

**Comment by pweyck** [comment]
We fixed it in https://github.com/shopware/production/commit/3fe268b4a603ae7aff4719db28852facefe59c13. You can keep using it no worries.

**Comment by bestit-ewieser** [comment]
Nice! Thanks for the update!
