### ISSUE TITLE
Docker image using wrong php-fpm pool configuration

### ISSUE THREAD

**Issue by fbdo** [shopware/production#21]
Hi Shopware contributors,

I am deploying Shopware 6 in a Kubernetes cluster, and for that I am using the provided Dockerfile to create the Docker image. When I was running a load test to check if my autoscaling rules were ok, I saw a growing % of response errors, and a warning in the logs saying:

> WARNING: [pool www] server reached pm.max_children setting (5), consider raising it.

I ran docker-compose locally, checked the php-fpm.d folder and I found 2 files with configurations for the same pool named [www]: www.conf and php-fpm.conf.

The Dockerfile copies the php-fpm.conf from the repo to the Docker image:

`
COPY config/etc /etc
`

But looks like Nginx install the www.conf file as well, and php-fpm pickups one.

I solved this issues renaming the file from php-fpm.conf to www.conf, so it overrides the existing file. I can provide a PR. What are your thoughts about it?

**Comment by pantrtxp** [comment]
Hi @fbdo,

we would really appreciate a PR if you already solved this :) 

Sunny regrads
Pantrtxp

**Comment by fbdo** [comment]
Hi @pantrtxp , I created the PR https://github.com/shopware/production/pull/22, I couldn't link it to this issue (permissions?), absolutely simple, could you check it?

**Comment by fbdo** [comment]
#22

**Comment by pantrtxp** [comment]
Hi @fbdo 

Thank you for you contribution. 
A colleague of mine will have a look at this in the future.

Sunny regards
Pantrtxp

**Comment by claudiobianco** [comment]
Sorry for double post, commented the PR:

Depending on how this is intended, you could also add it as "zz-fpm-pool.conf" in order to load it after "www.conf" (which is done alphabetically afaik) so that it will only override the included settings?

**Comment by shyim** [comment]
I would not change that Dockerfile anymore. The new template uses https://hub.docker.com/r/webdevops/php-apache, so we don't have to maintain a docker image anymore.

The new template:
https://github.com/shopware/docs/pull/760/files#diff-2525a2629f134228fc7d55615d5fbb517990de2c6ff9de903d5522d9fd25acf7
