### ISSUE TITLE
Add Docker image to Docker Hub

### ISSUE THREAD

**Issue by fbdo** [shopware/production#25]
Hi all!

I was planning to contribute a helm chart to all for Shopware 6 (you can see an initial draft [here](https://github.com/fbdo/charts/tree/master/shopware)). But I hit a stone: there's no public Docker image available at [Docker Hub](https://hub.docker.com/). I can see there's already a [Dockerfile](https://github.com/shopware/production/blob/6.1/Dockerfile), so, is it possible to deploy setup a pipeline to deploy it as well?

I already built my project using composer install and docker build in one of my build pipelines, but I used a private Docker registry to keep the image, would be really great to have the official image published publicly. I could do it, but as [Shopware already have a space there](https://hub.docker.com/u/shopware), I thought this step is probably trivial.

Let me know how I can help.

**Comment by fbdo** [comment]
Just an update: I created a [GitHub pipeline for now](https://github.com/fbdo/production/blob/add-docker-pipeline/.github/workflows/publish-docker-hub.yaml) and I started to publish in my own [Docker Hub space](https://hub.docker.com/r/fbdo/shopware). For now this setup helps me to test, but I would like to slowly move the code to the official channels.

**Comment by jnuricumbo** [comment]
@fbdo do you know where I find the instructions to run the containers? simply calling `docker-compose build && docker-compose up -d` does not work. Thank you

**Comment by ireznik** [comment]
@jnuricumbo try this Container: https://dockware.io/ it works quite well and you start it simply by  executing `docker-compose up -d`

**Comment by shyim** [comment]
@fbdo Maybe this helps?
https://github.com/shyim/shopware-image
https://github.com/shyim/shopware-chart

**Comment by shyim** [comment]
I would not change that Dockerfile anymore. The new template uses https://hub.docker.com/r/webdevops/php-apache, so we don't have to maintain a docker image anymore.

The new template:
https://github.com/shopware/docs/pull/760/files#diff-2525a2629f134228fc7d55615d5fbb517990de2c6ff9de903d5522d9fd25acf7
