### ISSUE TITLE
composer install/update fails on multi PHP Environment.

### ISSUE THREAD

**Issue by ascheider** [shopware/production#26]
Many hosting provider ships multiple PHP Versions on the server.
For example profihost:
`php -v
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.3.9, Copyright (c) 2002-2019, by ionCube Ltd.
    with Zend OPcache v7.0.33, Copyright (c) 1999-2017, by Zend Technologies`

There are also another PHP Version under different path:
/usr/local/php7.1/bin/php
/usr/local/php7.2/bin/php
/usr/local/php7.3/bin/php

If i ran composer install inside of the shopware directory with the custom PHP version it fails:
`/usr/local/php7.3/bin/php composer.phar install`

There is no PHP-executable before bin/console, so default 7.0 is used.
` "pre-install-cmd": [
            "[ ! -f vendor\/autoload.php ] || bin\/console system:update:prepare"
        ]`

The solution could be:
1. Define php-executable path for the project in .env file
2. Run bin/console commands from php-file with the php executable defined in .env file

**Comment by wrongspot** [comment]
I think that ist not a problem of composer or commands. Create a file in your home directory ".bash_profile" (if you have bash shell, for others it depends) with the following content. 
`export PATH=/usr/local/php7.3/bin:$PATH`

Restart your terminal and than your shell knows  which php version have to grab if you will run "php" from terminal.

**Comment by shopworksnl** [comment]
or create an alias in .bash_profile where php points to the php version you are using.

**Comment by ascheider** [comment]
@wrongspot @shopworksnl Thanks for suggestions. It could be the solution if you only have one shop installed on the target machine.
For example if i have 2 instances with different PHP-versions like local, multiple projects with different PHP-versions. So if i want to run composer install/update i need every time change my version in .profile to the desired one.

**Comment by DevertNet** [comment]
@ascheider For your local dev environment i would recommend ddev:
https://ddev.readthedocs.io/en/stable/

You can run every project with a different php, nginx, apache, mysql version and config.

**Comment by shyim** [comment]
Should be fixed by just using $PHP_BINARY env in the script

**Comment by shyim** [comment]
Fixed with https://github.com/shopware/production/commit/a94ea40d665aa9c401ba0a78d14a6151b7a2c909
