### ISSUE TITLE
malformed parameter "url"

### ISSUE THREAD

**Issue by macidev** [shopware/production#30]
Hi, 
during installation via 

`bin/console system:setup`

and entering "127.0.0.1" for database and "http://somefancyurl.tld/subfolder" i got the error 

> malformed parameter "url"

Runnin the web based installer via browser results in perfect running shop (after building admin and storefront). 

I got this twice on different servers and different urls.

**Comment by shyim** [comment]
I could not reproduce it anymore on the newest version.

**Comment by imagine6** [comment]
This happens when the Database password includes a question mark -> ?

**Comment by fxp** [comment]
> This happens when the Database password includes a question mark -> ?

Yes, I can re create the bug as well

**Comment by christoph-kluge** [comment]
I can confirm this bug on v6.4.6.1 with a password containing `#`

**Comment by weselben** [comment]
Yea i can confirm and reproduce both, still not fixed in Shopware v6-4-6-1

**Comment by keulinho** [comment]
Do you set the database-url with the `--database-url` option or do you configure the database connection through the interactive mode?

**Comment by christoph-kluge** [comment]
> Do you set the database-url with the `--database-url` option or do you configure the database connection through the interactive mode?

In my case it was through the interactive web interface.

**Comment by keulinho** [comment]
I can confirm that the UI installer currently has problems with `?` or `#` in the DB password.

I created a [ticket](https://issues.shopware.com/issues/NEXT-19088) for that and hopefully we can provide a fix shortly.
