### ISSUE TITLE
system:update:finish - Fails with migration identfier not found

### ISSUE THREAD

**Issue by AndreasA** [shopware/production#35]
When executing `system:update:finish` e.g. due to a `composer require` the command fails when it tries to execute migrations for `identifier` `Shopware\\` which makes sense as this is a namespace and not an identifier.

Shouldn't it just execute all migrations for all identifiers instead? And if not, wouldn't I at least need to add additional custom plugins there later on? For shopware it would instead be `core`, `Framework`, `StoreFront`, etc.?

**Comment by shyim** [comment]
Is fixed in meanwhile https://github.com/shopware/production/blob/6.3/src/Command/SystemUpdateFinishCommand.php#L82
