### ISSUE TITLE
6.2 RC 1 Wrong composer.lock file

### ISSUE THREAD

**Issue by DevertNet** [shopware/production#37]
Hey,

there is an error in the composer.lock file.
I always get this error:
`require(/var/www/html/vendor/composer/../shopware/core/Flag/feature_next6000.php): failed to open stream: No such file or directory in /var/www/html/vendor/composer/autoload_real.php on line 66`

After some debugging i found that this file i metioned in the composer.lock file:
https://github.com/shopware/production/blob/release/6.2.0-RC1/composer.lock#L4114

But the file "feature_next6000.php" is not in shopware/core:
https://github.com/shopware/core/tree/master/Flag

Best regards,
Leon

**Comment by shyim** [comment]
Has been fixed in meanwhile
