### ISSUE TITLE
6.2 RC 1 system:update:finish = No source registered for "Shopware\"

### ISSUE THREAD

**Issue by DevertNet** [shopware/production#38]
It looks that there was a few changes to the database migration system in 6.2.

It is possible that someone have forgot to change the system:update:finish command?
https://github.com/shopware/production/blob/cadcf3527ed834e9d5bbca283ca26dfdf825efbb/src/Command/SystemUpdateFinishCommand.php#L82

This
`'identifier' => 'Shopware\\',`

maybe should be 
`'identifier' => 'core',`
?

**Comment by mitelg** [comment]
duplicates https://github.com/shopware/production/issues/35
