### ISSUE TITLE
HTTP 413 when trying to upload large(r) images

### ISSUE THREAD

**Issue by rschindhelm** [shopware/production#41]
Hi,

we've been trying to evaluate Shopware v6.2 stable using Docker on our brand new server running Ubuntu 18.04.4 LTS and have trouble with the media gallery image upload. We've gone and changed the settings in config/etc/php7/conf.d/php.ini to allow for larger file uploads:

```
memory_limit            = 512M
post_max_size           = 64M
upload_max_filesize     = 48M
```

PHP's phpinfo() reflects the changes to the php.ini.

The upload of a 1280 by 720 pixels PNG graphic with a size of 2M fails. The admin center does not give a visual feedback as to wether the upload is in progress. After 20 or so seconds, when refreshing the page, a blank file is visible:

![image](https://user-images.githubusercontent.com/15197864/83801553-a3710b80-a6a9-11ea-8281-0ec82b84ccb2.png)

Selecting the blank file yields a "not found" error message:

![image](https://user-images.githubusercontent.com/15197864/83803385-bb965a00-a6ac-11ea-9c5e-80064a0ae6de.png)

Inspecting the logs yields a "HTTP 413 - Payload too large" error:

```
2020/06/04 19:17:03 [error] 17#17: *17 client intended to send too large body: 2177729 bytes, client: {ClientIP}, server: _, request: "POST /api/v1/_action/media/1b37c21746694df9b2c0fed3a95563d4/upload?extension=png&fileName=2.0+concept HTTP/1.1", host: "{ServerURL}", referrer: "{ServerURL}/admin"
{ClientIP} - - [04/Jun/2020:19:17:03 +0000] "POST /api/v1/_action/media/1b37c21746694df9b2c0fed3a95563d4/upload?extension=png&fileName=2.0+concept HTTP/1.1" 413 585 "{ServerURL}/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" "-" 0.386 - . -
```

Any clue as to what's happening here?

**Comment by shyim** [comment]
Do you have nginx?
Maybe forgot request_body_size

**Comment by rschindhelm** [comment]
> Do you have nginx?
> Maybe forgot request_body_size

Oh my. That's embarrassing :)
This solved the issue. Thank you.
