### ISSUE TITLE
composer dev-dependencies

### ISSUE THREAD

**Issue by 0x4** [shopware/production#44]
Since this is the "production" template no composer dev-dependencies should be needed

currently after running

`composer install --no-dev`

there are multiple errors because of refernced dev-components - e.g.
`php.CRITICAL: Uncaught Error: Class 'Symfony\Component\Stopwatch\Stopwatch' not found`

**Comment by shopworksnl** [comment]
see also https://github.com/shopware/production/pull/7

**Comment by shyim** [comment]
Will be fixed with the next Shopware update in Februray
