### ISSUE TITLE
[QUESTION] Top Sellers feature in Shopware 6

### ISSUE THREAD

**Issue by Kees-kees** [shopware/production#45]
Regarding Top Sellers -widely sold items- i was wondering if such a feature is expected to be developed in Shopware 6, as in Shopware 5 (slider block showing Top Sellers, and sorting products in category pages based on the total amount of sold items).

**Comment by mitelg** [comment]
Please use the [issue tracker](https://issues.shopware.com/) for Improvement suggestions
