### ISSUE TITLE
custom plugin folder is missing

### ISSUE THREAD

**Issue by FalkoHilbert** [shopware/production#5]
Hi,

unfortunately the custom / plugin folder is missing in the template and the configuration for it in composer.json.
Probably just a .gitkeep is missing here.
It would also be great if you already provided a distinction between store- and project-specific plugins.

**Comment by pweyck** [comment]
Hello @FalkoHilbert,

thanks for reporting this issue. It should be fixed in 6.1.1.

I'll also look into separating store- and project-specific plugins.
