### ISSUE TITLE
The "--no-cleanup" option does not exist

### ISSUE THREAD

**Issue by CSalih** [shopware/production#51]
**Describe the bug**
"post-install-cmd" in the composer.json calls the `system:update:finish` command. In this command there is the function `installAssets` witch calls the `assert:install` with a `--no-cleanup` flag.  
But in the [AssetInstallCommand](https://github.com/shopware/platform/commits/master/src/Core/Framework/Adapter/Asset/AssetInstallCommand.php) there is no `--no-cleanup` option, this causes a error described below.

**To Reproduce**
1. composer require *any-package*
2. Error -> See Additional context

**Actual behavior**
Error assets:install has no "--no-cleanup" option

**Expected behavior**
dependence installed and [OK] Successfully copied all bundle files

**Environment**
 - Version 6.3

**Additional context**
```
all migrations executed
cleared the shopware cache
14:07:54 ERROR     [console] Error thrown while running command "system:update:finish". Message: "The "--no-cleanup" option does not exist." ["exception" => Symfony\Component\Console\Exception\InvalidOptionException { …},"command" => "system:update:finish","message" => "The "--no-cleanup" option does not exist."]
     
  The "--no-cleanup" option does not exist.  
                                             
system:update:finish [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
``

**Comment by mitelg** [comment]
https://github.com/shopware/production/pull/50 fixes this problem
