### ISSUE TITLE
Webpack dev server: no login

### ISSUE THREAD

**Issue by datamints** [shopware/production#68]
When using the webpack dev server for the administration, the server starts up fine, the login page is shown but I'm never able to login: it makes the request for the token, but then just reloads the login screen.

The proxy of the webpack dev server is working fine, if I do the request for the token using curl or fetch (in the browser), I can see the token in the response.

**Comment by acydburn** [comment]
Do you use by any means a different HOST than localhost? There is a hardcoded value in shopware/administration/Resources/app/administration/index.html.tpl for the HOST so cookies are not set correctly. 

As a temporary fix you could change the bin/watch-administration.sh script and add something like:
`sed -i "s/host: '.*',/host: '$HOST',/g" ${PROJECT_ROOT}/vendor/shopware/administration/Resources/app/administration/index.html.tpl`

before the npm run command.

**Comment by shyim** [comment]
Meanwhile fixed
