### ISSUE TITLE
How to Setup and Configure

### ISSUE THREAD

**Issue by sawden** [shopware/production#73]
I tried to set up shopware with docker-compose but without success and a lot of pain.
Is a How to / documentation planned for this? Unfortunately I couldn't find anything.

**Comment by seriewe** [comment]
Hey, do you know the project: https://dockware.io/ this is super easy to use.  Maybe this is useful for you.

**Comment by codeplott** [comment]
Thank you for your answer. I am already using Dockware for development and I am very satisfied.
But there is no production image only "PLAY", "DEV", "CONTRIBUTE", "ESSENTIALS" and "FLEX".'

**Comment by dfsoeten** [comment]
Did you make any progress on this front @sawden? I'm having trouble setting up the database for local development using the production template. Adding `DATABASE_URL=mysql://root:root@mysql:3306/shopware` to the `app_server` service and `MYSQL_DATABASE=shopware` to the `mysql` service seems to connect. 

However, attempting to run `./bin/console` in the container results in the following:
```
./bin/console

In AbstractMySQLDriver.php line 42:

  An exception occurred while executing '            # dbal-plugin-loader
              SELECT
                     `name`,
                     `base_class` AS baseClass,
                     IF(`active` = 1 AND `installed_at` IS NOT NULL, 1, 0) AS active,
                     `path`,
                     `version`,
                     `autoload`,
                     `managed_by_composer` AS managedByComposer
              FROM `plugin`
              ORDER BY `installed_at`;':

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.plugin' doesn't exist


In PDOConnection.php line 80:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.plugin' doesn't exist


In PDOConnection.php line 75:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.plugin' doesn't exist

```

I'm not sure in which way I'm supposed to do the initial seeding of the database.

**Edit**: Alright, after some tinkering I have found a solution. To initialize the database run `bin/console system:install --create-database --basic-setup` in the container. Next, provide a `APP_SECRET` environment variable to your `app_server` service. Afterwards you can go to `localhost:8080/admin` and login with `admin` and `shopware`. Hopefully this helps someone!

**Comment by codeplott** [comment]
@dfsoeten 
Sorry for my late reply.

I am using the following project
https://github.com/shyim/shopware

It worked like a charm and my reported issue were fixed within 1-2 days
👍

**Comment by dfsoeten** [comment]
Thanks for your reply @sawden. It puzzels me that the repository you linked seem more elaborate and better thought out than the Docker environment in this repository. I've made some changes to the `docker-compose.yml`, `Dockerfile` and `bin/entrypoint.sh` and now have a (almost) fully automated Docker setup. 

I'll investigate the solution @shyim has implemented in his repository to see if I can improve my setup. Thanks for linking it!

**Comment by shyim** [comment]
Is this issue still relevant?
