### ISSUE TITLE
Media import, folder structure

### ISSUE THREAD

**Issue by ZigaVukcevicDev** [shopware/production#76]
Hi, this is more of a question.

I am trying to transfer media to another server/instance of shopware. I was thinking that copying media folder would be enough. If I inspect the same href on image:

a) current instance `media/e0/a7/27/1606814803/01n_bg.jpg`
b) new instance (with imported db from current instance) `media/2c/d8/20/1606814803/01n_bg.jpg`

I see that ids are the same, though uri structure differs.

Is this expected? Any help would be appreciated how to successfully transfer images.

**Comment by ZigaVukcevicDev** [comment]
I have solved this by using Shopware's Import/Export of media.

**Comment by m4m-simon** [comment]
I have the same problem. 

What i have figured out so far, with imported db from current instance :
- copy the media folder from shopware/development instance to another shopware/development instance WORKS
- copy the media folder from shopware/development instance to shopware/production instance DONT WORK

WHY does the URI structure differs from development and production template?? 
Is this intended behavior or can we fix this somehow?

**Comment by m4m-simon** [comment]
@be-codified could you reopen the issue? I think this behavior needs probably a real solution?

**Comment by m4m-simon** [comment]
okay here is the solution!
https://forum.shopware.com/t/hilfe-sind-wir-gehackt-worden-alle-bilder-sind-weg-weil-die-urls-sich-geandert-haben/67517/2

i quote @shyim (thanks!) in english:

Add the following to your .env file and delete the cache under /var/cache
`SHOPWARE_CDN_STRATEGY_DEFAULT=id`
if it does not work try
`SHOPWARE_CDN_STRATEGY_DEFAULT=physical_filename`
or
`SHOPWARE_CDN_STRATEGY_DEFAULT=filename`
These are the 3 possibilities for the strategy to form a path for images. One of them should work :)

**Comment by m4m-simon** [comment]
someone should add this to the docs
