### ISSUE TITLE
Production template + platform package

### ISSUE THREAD

**Issue by Atomschinken** [shopware/production#81]
While using composer together with the production template i stumbled upon some issues:

Some of the plugins we use require shopware/platform. As this package replaces core, storefront, administation and elasticsearch these are never downloaded. 

- `system:install` seems clever enough to check both paths (platform and core) for the schema.sql. the web based installer is not and throws an error.
- Another problem is `bin/console` as it only checks for the version of shopware/core although it has been replaced by the platform package. This can be fixed by catching the exception and use the platform version instead.

Is it not intended to use the platform package in a production-template-based project or am i overlooking something here?

Any help would be much appreciated.

**Comment by mitelg** [comment]
you should not require `shopware/platform` in your plugins. use `shopware/core` and if needed `shopware/storefront` and `shopware/administration`

your plugins will still work, if you use platform

**Comment by Atomschinken** [comment]
@mitelg Thank you for your response. I will contact the plugin author and request a change.

Despite from not being intended it is still technically possible to use the platform package. So it might be a good idea to handle this case anyway 😉

**Comment by mitelg** [comment]
yeah, you are right :+1: I will leave the issue open, regarding this point

**Comment by shyim** [comment]
It will be in the next week also disallowed in the store to require shopware/platform
