### ISSUE TITLE
"Composer install" simply does not work

### ISSUE THREAD

**Issue by aevedis** [shopware/production#83]
And this is what is being thrown in my terminal. I've followed instruction word by word

> [ ! -f vendor/autoload.php ] || bin/console system:update:prepare
'[' is not recognized as an internal or external command,
operable program or batch file.
'bin' is not recognized as an internal or external command,
operable program or batch file.
Script [ ! -f vendor/autoload.php ] || bin/console system:update:prepare handling the pre-install-cmd event returned with error code 1

**Comment by shyim** [comment]
Which OS?

**Comment by aevedis** [comment]
My bad, I had to add some extensions to my php.ini file. 

I leave them here for future reference:
`extension=php_fileinfo.dll
extension=php_gd2.dll
extension=intl
extension=pdo_mysql`

This issue shall now be closed 👍

**Comment by shyim** [comment]
Nice.
Take care we don't support Windows. Maybe look into WSL2 / Vagrant Solution when you are working on Windows
