### ISSUE TITLE
[QUESTION/CLARIFICATION/DOCUMENTATION] Theme/assets compile and build - what do I need to execute when exactly?

### ISSUE THREAD

**Issue by AndreasA** [shopware/production#84]
### Storefront

I have been wondering about this for some time:

- I have a project with a custom theme created myself.
- Now, I know that I can execute ./bin/build-js.sh or ./bin/build-storefront.sh to create the storefront JS dist file and also compile the thme.
- Is this created file the same as if I compile it in APP_ENV=prod mode? I already know that the dumped plugins.json file is different.
- If I have those files, is it enough to execute plugin:update on an automated deployment or do I also need to execute theme:compile and maybe also asset:install?
- If I have a custom font file, should that be placed in `dist` or `src` folder or doesn't it matter? I know that without either theme:compile and/or asset:install (did not check which of those two it was) it is not placed reachable with just a plugin update.
- Why should I actually include the JS file in the theme, shouldn't it be auto-generated? Especially, in a project where I use automated deployments? Or is that only necessary if I intend to upload the theme to the store?

It would be really helpful if this is explained in more details. Maybe in theme developer section of the documentation and also here.

From what I determined so far it seems that:
- For javascript changes, build-js.sh or ./bin/build-storefront.sh  has to be executed or it has to be executed always in case the JS file is not part of the git repository.
- For only scss changes, it mostly seems to be enough to do an update on the theme. Not sure if that is always the case.
- If assets of the theme change like e.g. not fonts etc. a theme:compile is necesary.
- Do I also have to execute asset:install prior to theme:compile.

Not sure though if that is correct.

### Admin

- ./bin/build-administration.sh or ./bin/build-js.sh has to be executed upon any changes to the admin's javascript files.
- If the `Resources/public/administration/*` files are included in the git repository/plugin, then a plugin update/install is enough to activate the administration changes.
- If that file is not included, then the build-administration.sh has to be executed.

Is that correct in regards to admin? If so, please add a documentation too.

### General

I really like that you defined what each command etc. does but it would be even more helpful to know when I have to execute which command. 
Also keep in mind automated deployments which like to build their assets on the fly and in which case you should also document if various files can be excluded from the repository like pre-compiled JS assets and what is the correct order etc. of steps to have everything working nicely. 
I think I found out the order but I am not sure if I need all of those steps or if I could skip some etc.

**Comment by shyim** [comment]
I know this issue is old. But are your questions still valid @AndreasA

**Comment by AndreasA** [comment]
@shyim If those things are now documented or otherwise solved (which I think they are as the documentation has been refactored a lot now), I think it can be closed. from my perspective I know most things now, doesn't mean it is not interesting for other persons.
