### ISSUE TITLE
system:setup - Now reports APP_URL missing upon exection - Probably regression

### ISSUE THREAD

**Issue by AndreasA** [shopware/production#86]
I know this worked in an older version, so it is probably a regression but with 6.3.5.0 it is not possible to call system:setup without providing `APP_URL` as env variable which does not make sense as that command is supposed to initialize those variables.

What works though is `APP_URL=http://localhost bin/console system:setup` but that seems unnecessary complicated. It then asks for the hostname again, so this is kind of weird.

**Comment by shopworksnl** [comment]
maybe same as https://issues.shopware.com/issues/NEXT-12476?

**Comment by AndreasA** [comment]
Probably, yes. But there is no issue here. I have been wondering about this multiple ways to post tickets/issues for a while now and in the Shopware issue tracker one cannot specify the that the issue is for the production template.

**Comment by shyim** [comment]
Duplicates #72
