### ISSUE TITLE
PHP8 support in 6.4 but composer.json only allows PHP 7.4

### ISSUE THREAD

**Issue by AndreasA** [shopware/production#91]
According to a commit PHP8 support was added in the `6.4` branch but according to the `composer.json` it only works with `>= 7.4.0` and `< 8`: https://github.com/shopware/production/blob/6.4/composer.json#L47

please add the corresponding `|| ^8.0`. You probably did not notice due to: https://github.com/shopware/production/issues

**Comment by JoshuaBehrens** [comment]
Why don't we just use php >= 7.4? Less hassle in the future

**Comment by mitelg** [comment]
@JoshuaBehrens bad idea 🙂
especially with the release of PHP 8 many repositories which had this version constraint broke, because they were just not compatible 😉 
in my opinion, every major release must be tested and could then separately declared in the composer.json

**Comment by AndreasA** [comment]
I agree, you always should test the supported version before adding them. As you do not know if your package works with it, which we know e.g. that Showpare 6.3 does not and if only because of it using dependencies.

This is also why I raised: https://github.com/shopware/production/issues/90

Because with that setting the PHP version constraint in the composer.json is completely ignored which is why that is a bad idea.

P.S.: I haven't checked Shopware6 platform/core etc. Those might also have the wrong PHP requirement for 8.x

Just checked it has't: https://github.com/shopware/platform/blob/b16f16c4a2e8ed0f32c7b3171f8fd04ca26edb2f/composer.json
same for core etc.

**Comment by JoshuaBehrens** [comment]
@mitelg oh yeah sorry, we are here in a project template 😅 . For the shopware/... packages I'd still question the constraints.

**Comment by AndreasA** [comment]
Especially for the shopware/... you need the constraints, As if one executes `composer require shopware/core` it should fail, if the user is using PHP 10.0, if it hasn't been confirmed to work with PHP 10.0 (Using 10.0 here by design).

If a user wants to bypass that constraint they can still use the `ignore-platform-reqs` parameter. Also, it is not like major PHP versions are released that often. It would be like using `"symfony/framework-bundle": ">= 4.4"` which would no install Symfony 5.2 but I am quite sure you did not yet test any Shopware packages with that version. Also `composer validate` actually doesn't like open constraints because of these reasons.

**Comment by JoshuaBehrens** [comment]
Open constraints are difficult to handle that is right. From a project implementation it is just a hassle to get every dependency into the right form to match the conglomerate of dependency hell. When there are less constraints those who merge the dependencies into a project have it easier.

**Comment by shyim** [comment]
https://github.com/shopware/production/commit/3b640c19bbe4d969fad28643269911016ebc1e1a
