### ISSUE TITLE
No installed assets after interactive installer: Admin panel doesn't work

### ISSUE THREAD

**Issue by rvzug** [shopware/production#93]
(branch=6.3)
While you install a production env. and use the 'interactive installer in the browser: /recovery/install/index.php'. (as instructed on [README.md](https://github.com/shopware/production#setup-and-install)) The assets are not installed.
When the wizzard completes, it redirects you to the admin-panel. Because the assets are not installed yet, the admin won't work and retuns 404's on all the assets.

Workaround:
``bin/console assets:install`` after completing the interactive installer
refresh the admin page

**Comment by rabauss** [comment]
I've got a similiar error on 6.4 without the installer! My admin panel is working but the assets of active plugins are not installed!

Unfortunately the ``assets:install`` while ``composer install`` does not recognize all active plugins. but if I run the command directly after ``composer install`` all assets of active bundles are copied!

I'm not sure if there needs to be something done to use all active plugins here:
https://github.com/shopware/production/blob/78819bc811ce0a27481b7143e916305243754e87/src/Command/SystemUpdateFinishCommand.php#L79

**Comment by shyim** [comment]
Hey,

We are working on a new template which does assets:install in a composer hook so this issue is definitively solved then

https://github.com/shopware/docs/pull/760/files#diff-2525a2629f134228fc7d55615d5fbb517990de2c6ff9de903d5522d9fd25acf7
